PATH:
  CDROM: "e:"
  ARCHIVE: "f:/Chess"
  IMPORT: "C:/Users/littl/Documents/ChessBase/Bases/import"
  
URL:
  TWIC_BASE: "https://theweekinchess.com/zips"

CBM:
  LAST: 215

TWIC:
  LAST: 919
  ATTEMPTS: 1

DEL_PATTERN:
  ARCHIVE: 
    - "*.msi"
    - "Autorun.inf"

  IMPORT:
    - "*Endgame*.*"
    - "*All in One*.*"
    - "*Start*.*"
    - "*Strategy*.*"
    - "*Tactics*.*"
    - "*Setup*.*"
    - "*.pdf"
    - "*text*.*"
